---
title: ChooseALicense.com
relative_permalinks: false
markdown: kramdown
url: "http://choosealicense.com"

collections:
  licenses:
    output: true
    permalink: /licenses/:path/

defaults:
  -
    scope:
      path: ""
      type: "licenses"
    values:
      layout: license
      featured: false
      "hide-from-license-list": false

exclude:
  - app.coffee
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - Rakefile
  - README.md
  - script
  - vendor/bundle
  - test
  - tests
  - assets/vendor/selectivizr/tests
  - assets/vendor/zeroclipboard/test
  
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
